@AiTesting.Api_HostAddress = http://localhost:5177

### Register user
POST {{AiTesting.Api_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "email": "oleg@example.com",
  "password": "StrongPass123!",
  "name": "Oleg"
}

### fadsfaf
POST {{AiTesting.Api_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "oleg@example.com",
  "password": "StrongPass123!"
}